#!/usr/bin/python
# 
# Exemplary script to read the annotations generated by the web application
# in this repo.
#
# @author: Luis Carlos Garcia-Peraza Herrera (luiscarlos.gph@gmail.com).
# @date  : 20 Jan 2021.

import argparse
import json
import cv2
import numpy as np
import os

# My imports
import wat.common

def parse_cmdline_params():
    """
    @brief Parse command line parameters to get input and output file names.
    @param[in] argv Array of command line arguments.  
    @return input and output file names if they were specified.
    """
    parser = argparse.ArgumentParser()
    parser.add_argument('--output-dir', required=True, help='Path to the output directory.')
    parser.add_argument('--gt-suffix', default='_seg', required=False, 
        help='Suffix of the segmentation-like annotations.')
    args = parser.parse_args()
    return args


def valid_cmdline_params(args):
    if not os.path.isdir(args.output_dir):
        raise ValueError('[ERROR] Output directory does not exist.')


def main():
    # Reading command line parameters
    args = parse_cmdline_params()
    valid_cmdline_params(args) 
    
    # List the data
    files = wat.common.listdir(args.output_dir, onlyfiles=True)
    images = [f for f in files if args.gt_suffix not in f and ('.png' in f or '.jpg' in f)]
    # TODO: jsons = []
    # TODO: segmentations = []
    
if __name__ == "__main__":
    main()
